### PR TITLE
Doppelganger role function.

### PR DESCRIPTION
**Pull request by tealidragon**
Moved distribute roles to doppelgänger phase (not sure I like this as it means doppelgänger phase is required even when doppelgänger role is not a part of a game).

Doppelgängers role becomes the role of the doppelgänged player.
 - Minion is tricky, but as minion only sees its 'Master(s) ...the werewolves...', doppelgänger minion won't know about the other minion and vice versa.
 - Masons and werewolves needs some fine tuning as it is returning the whole list of partners, rather than excluding the current player. (E.g.: You, player2, and player3 are your partners)
 - All other roles functioning as expected, need to double check how it works with the nightchoicesresults (branch: https://github.com/chodyo/one-night-ultimate-werewolf/tree/36-night-choice-results) , as seer, troublemaker, robber, and drunk doppelgänger will need to execute first before regular seer, troublemaker, robber, and drunk.

### CODE REVIEW

**Comment by chodyo** [comment]
> Moved distribute roles to doppelgänger phase

IMO we should reorder the phases.

1. Prep
2. Nighttime
3. Doppelganger
4. Probably need something here
5. Daytime

**Comment by sequestrian** [comment]
It makes a lot of sense to me for the Doppelgänger phase to come before other Nighttime actions and will fit quite well with the night action execution in my current implementation.

**Comment by chodyo** [comment]
> it is returning the whole list of partners

The client should know their own ID and be able to filter itself out. I'd 10000% prefer to send the same message to N players rather than having to fine tune each message for each player.

**Comment by sequestrian** [comment]
These changes were verified with unit tests and included in https://github.com/chodyo/one-night-ultimate-werewolf/pull/58

**Pull request closed without merging**
